name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    name: "windows-${{matrix.platform}}"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ x64, x86 ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install icu
      shell: pwsh
      run: |
        cd vcpkg
        ./bootstrap-vcpkg.bat
        ./vcpkg.exe --triplet=${{matrix.platform}}-windows `
                    --host-triplet=${{matrix.platform}}-windows `
                    install --recurse icu
    - uses: m-kuhn/action-tmate@patch-1
      if: always()
    - name: Package logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{matrix.platform}}
        path: ${{github.workspace}}/vcpkg/buildtrees/icu/**/*.log
